### ISSUE TITLE
Stock non raffraichis

### ISSUE THREAD

**Issue by Twister1one** [juxtamor/fiestaloca#11]
Quand on achete un produit et ont retourne sur le produit, le stock ne bouge pas.

**Comment by Twister1one** [comment]
les erreurs ne sont pas assez visible pour l'utilisateur, cela risque que celui-ci ai des incompréhension sur ces erreurs !

**Comment by Twister1one** [comment]
Bouton "DELETE" ne fonctionne pas dans notre panier !

**Comment by developpementjulio** [comment]
Le probleme de stock c'est reglé
