### ISSUE TITLE
[DB] comments > note

### ISSUE THREAD

**Issue by Shadownest** [juxtamor/fiestaloca#2]
https://github.com/juxtamor/fiestaloca/blob/master/fiestaloca.sql#L62

Utilisez plutôt un plus petit nombre, votre note n'atteindra jamais plus d'un milliard... elle sera sans doute de 1 voir 0 à 5 voir 10 ?

Un smallint c'est mieux :)

**Comment by juxtamor** [comment]
Modif ok, màj envoyée
