### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by Marouane90** [juxtamor/fiestaloca#21]
lorsqu'on inscrit une apostrophe il y'a une erreur

**Comment by Shadownest** [comment]
http://192.168.1.95/dev/eshop/fiestaloca/index.php?page=result&mot=%22%27&recherche=
( ! ) Warning: mysqli_fetch_object() expects parameter 1 to be mysqli_result, boolean given in /home/was1/sites/dev/eshop/fiestaloca/apps/result.php on line 15

**Comment by emeline1** [comment]
ok
