### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by titineo** [juxtamor/fiestaloca#25]
qd on est logué et que le panier est vide, dans la page panier: Fatal error: Call to a member function getProducts() on a non-object in /home/was1/sites/dev/eshop/fiestaloca/apps/cart_elem.php on line 6

**Comment by titineo** [comment]
même erreur qd on modifie l'url sur une page catégorie: http://192.168.1.95/dev/eshop/fiestaloca/index.php?page=products&id_category=2000000000000000000000000000000000000

erreur: Fatal error: Call to a member function getProducts() on a non-object in /home/was1/sites/dev/eshop/fiestaloca/apps/products.php on line 6

**Comment by mimimolette** [comment]
on a un Warning: mysqli_fetch_object() quand on met une recherche qui nexiste pas comme $_SESSION['] dans la barre de recherche
