### ISSUE TITLE
[MVC] Organisation

### ISSUE THREAD

**Issue by Shadownest** [juxtamor/fiestaloca#4]
Au lieu d'avoir les répertoires suivants à la racine de votre site :
css, fonts, images, js, scripts, styles

Mettez les dans un autre répertoire "public"

Ca sera moins bordelique.

PS : js == scripts && css == styles :)

**Comment by J2v-Informatique** [comment]
MAJ effectué, les éléments ont été modifiés

**Comment by Shadownest** [comment]
(J'en profite pour re-open)
Les anciens répertoires n'ont pas été supprimés !
