### ISSUE TITLE
[Class] Différents soucis

### ISSUE THREAD

**Issue by Shadownest** [juxtamor/fiestaloca#6]
Categorie.class.php
- [x] private $product; doit être au pluriel, il doit y avoir plusieurs produits dans une catégorie
- [x] Pas de getProducts ?

Command.class.php
- [x] Pas de vérification pour setTotalPrice ?
- [x] Paramètre invalide pour setTotalPrice

Product.class.php
- [x] private $id_category; n'est pas une propriété calculée, mais private $category; (qui manque) si.
- [x] getProdDesc() retourne la mauvaise propriété
- [x] setProduct(), wtf ? c'est setProdDesc() qu'il faudrait plutôt, attention aux fautes !
- [x] Aucune vérification pour setPrice() ?
- [x] Pour setImage() utilisez filter_var
- [x] Pour setStock(), je suis presque sûr que vous pouvez avoir un stock de 0 à moment donné... pourquoi mettre un minimum à 10 ?
- [x] Pour setStock() messages d'erreurs invalides
- [x] Pour setProdCover(), utilisez filter_var + messages d'erreurs invalides
- [x] Pour getComments(), attention à la valeur de retour (->comment) qui est fausse, et la propriété private $comments n'existe pas dans votre objet !
- [x] Pour getIdCategory(), il faut renommer la fonction en getCategory() tout court.
- [x] Pour setIdCategory(), pareil, c'est pas un $id_category qu'on doit gérer, mais une class Category !

User.class.php
- [x] Dans setPassword(), les conditions et les messages ne correspondent pas
- [x] Dans setAdress(), votre adresse n'est jamais valide ?
- [x] Dans setBirthdate(), il manque un message d'erreur

**Comment by developpementjulio** [comment]
Erreurs corrigés à verifier stp

**Comment by juxtamor** [comment]
MàJ ok, to check
