### ISSUE TITLE
[Class] Encore des modifs

### ISSUE THREAD

**Issue by Shadownest** [juxtamor/fiestaloca#8]
Categorie.class.php
- [x] Encore un petit effort pour getProducts()

Product.class.php
- [x] setPrice() est pas encore complètement correct, pas besoin du return à la dernière ligne de la fonction
- [x] setImage(), regardez comment on a utiliser filter_var dans les autres projets, là c'est faux
- [x] setProdCover(), pareil, filter_var

User.class.php
- [x] Il manque le constructeur et private $db;

Command.class.php
- [x] setStatus(), va peut être falloir rajouter une vérification, à voir selon votre projet
- [x] setTotalPrice(), est encore faux pour le moment

**Comment by developpementjulio** [comment]
Pascal, tu pourrais verifier le fichier  Product.class.php et Product.class.php stp?
